# 介绍
针对A股因子研究和交易分析场景，提供了常用的小工具，如查询历史的交易日，历史的行业分类表等

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_config = {
"remote.data.address": "tcp://data.tushare.org:8910",
"remote.data.username": "18566262672",
"remote.data.password": "eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVfdGltZSI6IjE1MTI3MDI3NTAyMTIiLCJpc3MiOiJhdXRoMCIsImlkIjoiMTg1NjYyNjI2NzIifQ.O_-yR0zYagrLRvPbggnru1Rapk4kiyAzcwYt2a3vlpM"
}

from jaqs_fxdayu.data import DataApi

api = DataApi(data_config["remote.data.address"]) # 传入连接到的远端数据服务器的tcp地址
api.login(username=data_config["remote.data.username"],
          password=data_config["remote.data.password"])

('username: 18566262672', '0,')

## trade_days
- ` jaqs_fxdayu.utils.dp.trade_days(api, start, end) `

**简要描述：**

- 返回起止日期间的交易日

**参数:**

|字段|必选|类型|说明|
|:----    |:---|:----- |-----   |
|api |是| jaqs.data.DataApi |jaqs.data.DataApi|
|start |是|int |开始日期|
|end |是|int |结束日期|

**返回:**

起止日期间的交易日

**示例：**

In [3]:
from jaqs_fxdayu.utils.dp import trade_days
trade_days(api, 20170101, 20180101)

Int64Index([20170103, 20170104, 20170105, 20170106, 20170109, 20170110,
            20170111, 20170112, 20170113, 20170116,
            ...
            20171218, 20171219, 20171220, 20171221, 20171222, 20171225,
            20171226, 20171227, 20171228, 20171229],
           dtype='int64', name='trade_date', length=244)

## index_cons
- ` jaqs_fxdayu.utils.dp.index_cons(api, index_code, start, end) `

**简要描述：**

- 获得某个指数起止时间段的历史成分股信息

**参数:**

|字段|必选|类型|说明|
|:----    |:---|:----- |-----   |
|api |是| jaqs.data.DataApi |jaqs.data.DataApi|
|index_code |是| str |指数代码|
|start |是|int |开始日期|
|end |是|int |结束日期|

**返回:**

某个指数起止时间段的历史成分股信息

- 其中 in_date:纳入该指数的时间；out_date:从该指数移除的时间

**示例：**

In [8]:
from jaqs_fxdayu.utils.dp import index_cons
index_cons(api, "000300.SH", 20170101, 20170501).head()

    in_date index_code  out_date     symbol
0  20050408  000300.SH  99999999  000001.SZ
1  20050408  000300.SH  99999999  000002.SZ
2  20161212  000300.SH  99999999  000008.SZ
3  20050408  000300.SH  20171208  000009.SZ
4  20140616  000300.SH  20170609  000027.SZ

## daily_index_cons
- ` jaqs_fxdayu.utils.dp.daily_index_cons(api, index_code, start, end) `

**简要描述：**

- 指定起止时间段，成分股是否还在某指数当中

**参数:**

|字段|必选|类型|说明|
|:----    |:---|:----- |-----   |
|api |是| jaqs.data.DataApi |jaqs.data.DataApi|
|index_code |是| str |指数代码|
|start |是|int |开始日期|
|end |是|int |结束日期|

**示例：**

In [9]:
from jaqs_fxdayu.utils.dp import daily_index_cons
daily_index_cons(api, "000300.SH", 20170101, 20170501).head()

,000001.SZ,000002.SZ,000008.SZ,000009.SZ,000027.SZ,000039.SZ,000060.SZ,000061.SZ,000063.SZ,000069.SZ,...,601933.SH,601939.SH,601958.SH,601985.SH,601988.SH,601989.SH,601998.SH,603000.SH,603885.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20170103,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
20170104,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
20170105,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
20170106,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
20170109,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

## daily_sec_industry
- ` jaqs_fxdayu.utils.dp.daily_sec_industry(api, symbol, start, end, source="sw", value="industry1_code") `

**简要描述：**

- 指定起始时间段，查询某一系列股票在该时间段下的行业分类信息

**参数:**

|字段|必选|类型|说明|
|:----    |:---|:----- |-----   |
|api |是| jaqs.data.DataApi |jaqs.data.DataApi|
|symbol |是| str |股票代码，用","隔开。如"600000.SH,000001.SZ"|
|start |是|int |开始日期|
|end |是|int |结束日期|
|source |否|str |行业分类标准，目前仅支持"sw"(申万),"zz"(中证),"zjh"（证监会）,默认"sw"|
|value |否|str |行业等级，形式可为"industry?_code"(行业编码)/"industry?_name"(行业名称)。其中"?"可为1,2,3,4,分别代表1-4个行业等级。申万支持1-4,中证支持1-2。默认为industry1_code|

**示例：**

In [17]:
from jaqs_fxdayu.utils.dp import daily_sec_industry
symbol_id = index_cons(api, "000300.SH", 20170501, 20171001,)["symbol"].dropna()
symbols = ",".join(symbol_id)
group = daily_sec_industry(api, symbols, 20170501, 20171001, source='zjh', value="industry1_name")
group.tail()

,000001.SZ,000002.SZ,000008.SZ,000009.SZ,000027.SZ,000039.SZ,000060.SZ,000061.SZ,000063.SZ,000069.SZ,...,601988.SH,601989.SH,601992.SH,601997.SH,601998.SH,603000.SH,603160.SH,603858.SH,603885.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20170925,金融业,房地产业,制造业,综合,电力、热力、燃气及水生产和供应业,制造业,制造业,租赁和商务服务业,制造业,水利、环境和公共设施管理业,...,金融业,制造业,制造业,金融业,金融业,信息传输、软件和信息技术服务业,制造业,制造业,交通运输、仓储和邮政业,采矿业
20170926,金融业,房地产业,制造业,综合,电力、热力、燃气及水生产和供应业,制造业,制造业,租赁和商务服务业,制造业,水利、环境和公共设施管理业,...,金融业,制造业,制造业,金融业,金融业,信息传输、软件和信息技术服务业,制造业,制造业,交通运输、仓储和邮政业,采矿业
20170927,金融业,房地产业,制造业,综合,电力、热力、燃气及水生产和供应业,制造业,制造业,租赁和商务服务业,制造业,水利、环境和公共设施管理业,...,金融业,制造业,制造业,金融业,金融业,信息传输、软件和信息技术服务业,制造业,制造业,交通运输、仓储和邮政业,采矿业
20170928,金融业,房地产业,制造业,综合,电力、热力、燃气及水生产和供应业,制造业,制造业,租赁和商务服务业,制造业,水利、环境和公共设施管理业,...,金融业,制造业,制造业,金融业,金融业,信息传输、软件和信息技术服务业,制造业,制造业,交通运输、仓储和邮政业,采矿业
20170929,金融业,房地产业,制造业,综合,电力、热力、燃气及水生产和供应业,制造业,制造业,租赁和商务服务业,制造业,水利、环境和公共设施管理业,...,金融业,制造业,制造业,金融业,金融业,信息传输、软件和信息技术服务业,制造业,制造业,交通运输、仓储和邮政业,采矿业